### PR TITLE
card-template-project

### PR DESCRIPTION
**Pull request by santoshsingh19114**

### CODE REVIEW

**Comment by Ayush-2301** [comment]
@santoshsingh19114 create a branch of your name then make a PR through that branch

**Comment by santoshsingh19114** [comment]
Document - Google Chrome 16-06-2023 20_49_00

**Comment by santoshsingh19114** [comment]
sir facing some issue while pushing the project through branch

**Comment by Ayush-2301** [comment]
dm me @santoshsingh19114

**Pull request closed without merging**
